// This file is auto-generated by @hey-api/openapi-ts

import {
  buildClientParams,
  type Client,
  type ClientMeta,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
} from './client'
import { client } from './client.gen'
import type {
  CanvasContentRequest,
  DeviceSettingsRequest,
  DisplayCanvasErrors,
  DisplayCanvasResponses,
  DisplayImageErrors,
  DisplayImageResponses,
  DisplayTextErrors,
  DisplayTextResponses,
  GetDeviceSettingsErrors,
  GetDeviceSettingsResponses,
  GetDeviceStatusErrors,
  GetDeviceStatusResponses,
  ImageContentRequest,
  ListDevicesErrors,
  ListDevicesResponses,
  ListDeviceTasksErrors,
  ListDeviceTasksResponses,
  ListTimezonesErrors,
  ListTimezonesResponses,
  SwitchNextContentErrors,
  SwitchNextContentResponses,
  TextContentRequest,
  UpdateDeviceSettingsErrors,
  UpdateDeviceSettingsResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * List Dot. devices.
 *
 * Get all Dot. devices associated with the authenticated account.
 */
export const listDevices = <ThrowOnError extends boolean = false>(
  options?: Options<never, ThrowOnError>,
): RequestResult<ListDevicesResponses, ListDevicesErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListDevicesResponses, ListDevicesErrors, ThrowOnError>({
    security: [
      {
        key: 'bearerAuth',
        scheme: 'bearer',
        type: 'http',
      },
      {
        key: 'oauth2',
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/authV2/open/devices',
    ...options,
  })

/**
 * List supported timezones.
 *
 * Get timezone keys accepted by device settings APIs.
 */
export const listTimezones = <ThrowOnError extends boolean = false>(
  options?: Options<never, ThrowOnError>,
): RequestResult<ListTimezonesResponses, ListTimezonesErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListTimezonesResponses, ListTimezonesErrors, ThrowOnError>({
    security: [
      {
        key: 'bearerAuth',
        scheme: 'bearer',
        type: 'http',
      },
      {
        key: 'oauth2',
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/authV2/open/timezones',
    ...options,
  })

/**
 * Get device status.
 *
 * Get current battery, Wi-Fi, display, and render information for a Dot. device.
 */
export const getDeviceStatus = <ThrowOnError extends boolean = false>(
  parameters: {
    deviceId: string
  },
  options?: Options<never, ThrowOnError>,
): RequestResult<GetDeviceStatusResponses, GetDeviceStatusErrors, ThrowOnError> => {
  const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'deviceId' }] }])
  return (options?.client ?? client).get<
    GetDeviceStatusResponses,
    GetDeviceStatusErrors,
    ThrowOnError
  >({
    security: [
      {
        key: 'bearerAuth',
        scheme: 'bearer',
        type: 'http',
      },
      {
        key: 'oauth2',
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/authV2/open/device/{deviceId}/status',
    ...options,
    ...params,
  })
}

/**
 * Get device settings.
 *
 * Get editable settings for a Dot. device owned by the authenticated account.
 */
export const getDeviceSettings = <ThrowOnError extends boolean = false>(
  parameters: {
    deviceId: string
  },
  options?: Options<never, ThrowOnError>,
): RequestResult<GetDeviceSettingsResponses, GetDeviceSettingsErrors, ThrowOnError> => {
  const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'deviceId' }] }])
  return (options?.client ?? client).get<
    GetDeviceSettingsResponses,
    GetDeviceSettingsErrors,
    ThrowOnError
  >({
    security: [
      {
        key: 'bearerAuth',
        scheme: 'bearer',
        type: 'http',
      },
      {
        key: 'oauth2',
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/authV2/open/device/{deviceId}/settings',
    ...options,
    ...params,
  })
}

/**
 * Update device settings.
 *
 * Update one or more settings for a Dot. device owned by the authenticated account.
 * Only POST is supported for writes. Omitted fields are left unchanged.
 *
 */
export const updateDeviceSettings = <ThrowOnError extends boolean = false>(
  parameters: {
    deviceId: string
    deviceSettingsRequest: DeviceSettingsRequest
  },
  options?: Options<never, ThrowOnError>,
): RequestResult<UpdateDeviceSettingsResponses, UpdateDeviceSettingsErrors, ThrowOnError> => {
  const params = buildClientParams(
    [parameters],
    [
      {
        args: [
          { in: 'path', key: 'deviceId' },
          { key: 'deviceSettingsRequest', map: 'body' },
        ],
      },
    ],
  )
  return (options?.client ?? client).post<
    UpdateDeviceSettingsResponses,
    UpdateDeviceSettingsErrors,
    ThrowOnError
  >({
    security: [
      {
        key: 'bearerAuth',
        scheme: 'bearer',
        type: 'http',
      },
      {
        key: 'oauth2',
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/authV2/open/device/{deviceId}/settings',
    ...options,
    ...params,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
      ...params.headers,
    },
  })
}

/**
 * Switch to next content.
 *
 * Immediately switch the device to the next content item in its rotation.
 */
export const switchNextContent = <ThrowOnError extends boolean = false>(
  parameters: {
    deviceId: string
  },
  options?: Options<never, ThrowOnError>,
): RequestResult<SwitchNextContentResponses, SwitchNextContentErrors, ThrowOnError> => {
  const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'deviceId' }] }])
  return (options?.client ?? client).post<
    SwitchNextContentResponses,
    SwitchNextContentErrors,
    ThrowOnError
  >({
    security: [
      {
        key: 'bearerAuth',
        scheme: 'bearer',
        type: 'http',
      },
      {
        key: 'oauth2',
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/authV2/open/device/{deviceId}/next',
    ...options,
    ...params,
  })
}

/**
 * Display text content.
 *
 * Display text content on a Dot. device. The device must already have a Text API
 * content item in its loop task in Dot. App Content Studio.
 *
 */
export const displayText = <ThrowOnError extends boolean = false>(
  parameters: {
    deviceId: string
    textContentRequest: TextContentRequest
  },
  options?: Options<never, ThrowOnError>,
): RequestResult<DisplayTextResponses, DisplayTextErrors, ThrowOnError> => {
  const params = buildClientParams(
    [parameters],
    [
      {
        args: [
          { in: 'path', key: 'deviceId' },
          { key: 'textContentRequest', map: 'body' },
        ],
      },
    ],
  )
  return (options?.client ?? client).post<DisplayTextResponses, DisplayTextErrors, ThrowOnError>({
    security: [
      {
        key: 'bearerAuth',
        scheme: 'bearer',
        type: 'http',
      },
      {
        key: 'oauth2',
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/authV2/open/device/{deviceId}/text',
    ...options,
    ...params,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
      ...params.headers,
    },
  })
}

/**
 * Display image content.
 *
 * Display PNG image content on a Dot. device. The device must already have an Image API
 * content item in its loop task in Dot. App Content Studio.
 *
 */
export const displayImage = <ThrowOnError extends boolean = false>(
  parameters: {
    deviceId: string
    imageContentRequest: ImageContentRequest
  },
  options?: Options<never, ThrowOnError>,
): RequestResult<DisplayImageResponses, DisplayImageErrors, ThrowOnError> => {
  const params = buildClientParams(
    [parameters],
    [
      {
        args: [
          { in: 'path', key: 'deviceId' },
          { key: 'imageContentRequest', map: 'body' },
        ],
      },
    ],
  )
  return (options?.client ?? client).post<DisplayImageResponses, DisplayImageErrors, ThrowOnError>({
    security: [
      {
        key: 'bearerAuth',
        scheme: 'bearer',
        type: 'http',
      },
      {
        key: 'oauth2',
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/authV2/open/device/{deviceId}/image',
    ...options,
    ...params,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
      ...params.headers,
    },
  })
}

/**
 * Display Canvas API content.
 *
 * Display a custom Canvas API layout on a Dot. device. The device must already have a
 * Canvas API content item in its loop task in Dot. App Content Studio.
 *
 */
export const displayCanvas = <ThrowOnError extends boolean = false>(
  parameters: {
    deviceId: string
    canvasContentRequest: CanvasContentRequest
  },
  options?: Options<never, ThrowOnError>,
): RequestResult<DisplayCanvasResponses, DisplayCanvasErrors, ThrowOnError> => {
  const params = buildClientParams(
    [parameters],
    [
      {
        args: [
          { in: 'path', key: 'deviceId' },
          { key: 'canvasContentRequest', map: 'body' },
        ],
      },
    ],
  )
  return (options?.client ?? client).post<
    DisplayCanvasResponses,
    DisplayCanvasErrors,
    ThrowOnError
  >({
    security: [
      {
        key: 'bearerAuth',
        scheme: 'bearer',
        type: 'http',
      },
      {
        key: 'oauth2',
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/authV2/open/device/{deviceId}/canvas',
    ...options,
    ...params,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
      ...params.headers,
    },
  })
}

/**
 * List device tasks.
 *
 * List loop or fixed tasks for a Dot. device.
 */
export const listDeviceTasks = <ThrowOnError extends boolean = false>(
  parameters: {
    deviceId: string
    taskType: 'loop' | 'fixed'
  },
  options?: Options<never, ThrowOnError>,
): RequestResult<ListDeviceTasksResponses, ListDeviceTasksErrors, ThrowOnError> => {
  const params = buildClientParams(
    [parameters],
    [
      {
        args: [
          { in: 'path', key: 'deviceId' },
          { in: 'path', key: 'taskType' },
        ],
      },
    ],
  )
  return (options?.client ?? client).get<
    ListDeviceTasksResponses,
    ListDeviceTasksErrors,
    ThrowOnError
  >({
    security: [
      {
        key: 'bearerAuth',
        scheme: 'bearer',
        type: 'http',
      },
      {
        key: 'oauth2',
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/authV2/open/device/{deviceId}/{taskType}/list',
    ...options,
    ...params,
  })
}
