// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://dot.mindreset.tech' | (string & {})
}

export type Device = {
  /**
   * Device alias.
   */
  alias?: string | null
  /**
   * Device location.
   */
  location?: string | null
  series?: string
  model?: string
  edition?: number
  /**
   * Device serial number.
   */
  id?: string
  [key: string]: unknown
}

export type Timezone = {
  key: TimezoneKey
  name: string
  utcOffsetMinutes: number
  utcOffsetLabel: string
}

/**
 * Supported IANA timezone key. Use List Timezones for the full localized list.
 */
export type TimezoneKey =
  | 'Pacific/Midway'
  | 'Pacific/Honolulu'
  | 'America/Anchorage'
  | 'America/Los_Angeles'
  | 'America/Phoenix'
  | 'America/Denver'
  | 'America/Chicago'
  | 'America/New_York'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Argentina/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Europe/London'
  | 'Europe/Dublin'
  | 'Europe/Paris'
  | 'Europe/Rome'
  | 'Europe/Berlin'
  | 'Europe/Madrid'
  | 'Europe/Athens'
  | 'Europe/Moscow'
  | 'Asia/Dubai'
  | 'Asia/Kabul'
  | 'Asia/Karachi'
  | 'Asia/Kolkata'
  | 'Asia/Kathmandu'
  | 'Asia/Dhaka'
  | 'Asia/Yangon'
  | 'Asia/Bangkok'
  | 'Asia/Singapore'
  | 'Asia/Shanghai'
  | 'Asia/Hong_Kong'
  | 'Asia/Taipei'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Adelaide'
  | 'Australia/Darwin'
  | 'Australia/Sydney'
  | 'Australia/Brisbane'
  | 'Pacific/Guam'
  | 'Australia/Hobart'
  | 'Pacific/Port_Moresby'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'
  | 'Pacific/Tongatapu'
  | 'Pacific/Apia'
  | 'Pacific/Kiritimati'
  | 'America/Tijuana'
  | 'America/Mexico_City'
  | 'America/Monterrey'
  | 'America/Bogota'
  | 'America/Lima'
  | 'America/La_Paz'
  | 'America/Montevideo'
  | 'America/Halifax'
  | 'America/St_Johns'
  | 'Europe/Lisbon'
  | 'Europe/Warsaw'
  | 'Europe/Prague'
  | 'Europe/Budapest'
  | 'Europe/Bucharest'
  | 'Europe/Kiev'
  | 'Europe/Istanbul'
  | 'Asia/Tehran'
  | 'Asia/Kuwait'
  | 'Asia/Baghdad'
  | 'Asia/Riyadh'
  | 'Asia/Jerusalem'
  | 'Asia/Colombo'
  | 'Asia/Jakarta'
  | 'Asia/Manila'
  | 'Asia/Kuala_Lumpur'
  | 'Asia/Ulaanbaatar'
  | 'Asia/Yakutsk'
  | 'Asia/Vladivostok'
  | 'Asia/Magadan'
  | 'Asia/Kamchatka'
  | 'Australia/Perth'
  | 'Australia/Melbourne'
  | 'Pacific/Chatham'
  | 'Pacific/Marquesas'
  | 'Africa/Cairo'
  | 'Africa/Johannesburg'
  | 'Africa/Lagos'
  | 'Africa/Nairobi'
  | 'Africa/Casablanca'
  | 'America/Toronto'
  | 'America/Vancouver'
  | 'America/Winnipeg'
  | 'America/Edmonton'

export type DeviceStatusResponse = {
  deviceId?: string
  alias?: string | null
  location?: string | null
  status?: {
    version?: string
    current?: string
    description?: string
    battery?: string
    wifi?: string
    [key: string]: unknown
  }
  renderInfo?: {
    [key: string]: unknown
  }
  [key: string]: unknown
}

export type DeviceSettingsRequest = {
  /**
   * Device alias. Send null or an empty string to clear it.
   */
  alias?: string | null
  /**
   * Device location. Send null or an empty string to clear it.
   */
  location?: string | null
  timezone?: TimezoneKey
  interval?: DeviceSettingsInterval
  sleep?: DeviceSettingsSleep
}

export type DeviceSettingsInterval = {
  /**
   * Refresh interval in milliseconds while connected to power.
   */
  powerMs?: number
  /**
   * Automatic wake and refresh interval in milliseconds while using battery power.
   */
  batteryMs?: number
}

export type DeviceSettingsSleep = {
  enabled: boolean
  /**
   * Local wall-clock start time in the device timezone.
   */
  start: string
  /**
   * Local wall-clock end time in the device timezone. If earlier than start, it means the next day.
   */
  end: string
}

export type DeviceSettingsResponse = {
  deviceId: string
  alias: string | null
  location: string | null
  timezone: TimezoneKey
  interval: DeviceSettingsInterval
  sleep: DeviceSettingsSleep | null
}

export type TextContentRequest = {
  refreshNow?: boolean
  taskKey?: string
  taskAlias?: TaskAlias
  title?: string
  /**
   * Main content text. Supports newline and tab characters.
   */
  message?: string
  signature?: string
  /**
   * Optional PNG icon. Send either bare PNG Base64, a data:image/png;base64, data URL, or a full http(s) image URL. Base64 payloads must decode to at most 1MB. Remote URLs must be anonymously accessible, no longer than 2048 characters, return an image* response body, and the response body must be at most 3MB.
   */
  icon?: string
  link?: string
  styles?: {
    title?: TextStyle
    message?: MessageTextStyle
    signature?: TextStyle
  }
}

export type TextStyle = {
  fontFamily?: string
  fontSize?: number
  fontWeight?: 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900
}

export type MessageTextStyle = TextStyle & {
  lineHeight?: number
}

export type ImageContentRequest = {
  refreshNow?: boolean
  taskKey?: string
  taskAlias?: TaskAlias
  /**
   * Required image content. Send either bare PNG Base64, a data:image/png;base64, data URL, or a full http(s) image URL. Base64 payloads must decode to at most 3MB. Remote URLs must be anonymously accessible, no longer than 2048 characters, return an image* response body, and the response body must be at most 3MB.
   */
  image: string
  link?: string
  border?: Border
  ditherType?: 'DIFFUSION' | 'ORDERED' | 'NONE'
  ditherKernel?: DitherKernel
}

export type CanvasContentRequest = {
  refreshNow?: boolean
  taskKey?: string
  taskAlias?: TaskAlias
  /**
   * Plain JSON values read by the Canvas layout.
   */
  data?: {
    [key: string]: unknown
  }
  windowData: CanvasWindowData
  /**
   * FULL layout override with optional `tw` and `style`.
   */
  layoutFull?: {
    [key: string]: unknown
  }
  link?: string
  border?: Border
}

export type CanvasWindowData = {
  default: Array<CanvasElement>
  [key: string]: unknown
}

export type CanvasElement = {
  type: 'div' | 'span' | 'img'
  /**
   * Canvas render props such as `tw`, `style`, and `children`.
   */
  props: {
    [key: string]: unknown
  }
}

export type DeviceTask = {
  type?: 'TEXT_API' | 'IMAGE_API' | 'CANVAS_API' | 'GENERAL'
  /**
   * Task unique identifier. Use as `taskKey` for content requests.
   */
  key?: string | null
  refreshNow?: boolean
  taskAlias?: TaskAlias
  [key: string]: unknown
}

/**
 * Human-readable task name shown in the device task list.
 */
export type TaskAlias = string | number

/**
 * Screen border color. 0 is white, 1 is black.
 */
export type Border = 0 | 1

export type DitherKernel =
  | 'THRESHOLD'
  | 'ATKINSON'
  | 'BURKES'
  | 'FLOYD_STEINBERG'
  | 'SIERRA2'
  | 'STUCKI'
  | 'JARVIS_JUDICE_NINKE'
  | 'DIFFUSION_ROW'
  | 'DIFFUSION_COLUMN'
  | 'DIFFUSION_2D'

export type MessageResponse = {
  message?: string
  [key: string]: unknown
}

export type ErrorResponse = {
  message?: string
  [key: string]: unknown
}

/**
 * Dot. device serial number.
 */
export type DeviceId = string

export type ListDevicesData = {
  body?: never
  path?: never
  query?: never
  url: '/api/authV2/open/devices'
}

export type ListDevicesErrors = {
  /**
   * Invalid or missing API key.
   */
  401: ErrorResponse
  /**
   * Rate limit exceeded. Limit is 10 requests per second.
   */
  429: ErrorResponse
}

export type ListDevicesError = ListDevicesErrors[keyof ListDevicesErrors]

export type ListDevicesResponses = {
  /**
   * Devices associated with the account.
   */
  200: Array<Device>
}

export type ListDevicesResponse = ListDevicesResponses[keyof ListDevicesResponses]

export type ListTimezonesData = {
  body?: never
  path?: never
  query?: never
  url: '/api/authV2/open/timezones'
}

export type ListTimezonesErrors = {
  /**
   * Invalid or missing API key.
   */
  401: ErrorResponse
  /**
   * Rate limit exceeded. Limit is 10 requests per second.
   */
  429: ErrorResponse
}

export type ListTimezonesError = ListTimezonesErrors[keyof ListTimezonesErrors]

export type ListTimezonesResponses = {
  /**
   * Supported timezones.
   */
  200: Array<Timezone>
}

export type ListTimezonesResponse = ListTimezonesResponses[keyof ListTimezonesResponses]

export type GetDeviceStatusData = {
  body?: never
  path: {
    /**
     * Dot. device serial number.
     */
    deviceId: string
  }
  query?: never
  url: '/api/authV2/open/device/{deviceId}/status'
}

export type GetDeviceStatusErrors = {
  /**
   * Invalid or missing API key.
   */
  401: ErrorResponse
  /**
   * Device or resource not found.
   */
  404: ErrorResponse
  /**
   * Rate limit exceeded. Limit is 10 requests per second.
   */
  429: ErrorResponse
}

export type GetDeviceStatusError = GetDeviceStatusErrors[keyof GetDeviceStatusErrors]

export type GetDeviceStatusResponses = {
  /**
   * Current device status.
   */
  200: DeviceStatusResponse
}

export type GetDeviceStatusResponse = GetDeviceStatusResponses[keyof GetDeviceStatusResponses]

export type GetDeviceSettingsData = {
  body?: never
  path: {
    /**
     * Dot. device serial number.
     */
    deviceId: string
  }
  query?: never
  url: '/api/authV2/open/device/{deviceId}/settings'
}

export type GetDeviceSettingsErrors = {
  /**
   * Invalid or missing API key.
   */
  401: ErrorResponse
  /**
   * Device or resource not found.
   */
  404: ErrorResponse
  /**
   * Rate limit exceeded. Limit is 10 requests per second.
   */
  429: ErrorResponse
}

export type GetDeviceSettingsError = GetDeviceSettingsErrors[keyof GetDeviceSettingsErrors]

export type GetDeviceSettingsResponses = {
  /**
   * Current device settings.
   */
  200: DeviceSettingsResponse
}

export type GetDeviceSettingsResponse = GetDeviceSettingsResponses[keyof GetDeviceSettingsResponses]

export type UpdateDeviceSettingsData = {
  body: DeviceSettingsRequest
  path: {
    /**
     * Dot. device serial number.
     */
    deviceId: string
  }
  query?: never
  url: '/api/authV2/open/device/{deviceId}/settings'
}

export type UpdateDeviceSettingsErrors = {
  /**
   * Invalid request parameters.
   */
  400: ErrorResponse
  /**
   * Invalid or missing API key.
   */
  401: ErrorResponse
  /**
   * Device or resource not found.
   */
  404: ErrorResponse
  /**
   * Rate limit exceeded. Limit is 10 requests per second.
   */
  429: ErrorResponse
}

export type UpdateDeviceSettingsError = UpdateDeviceSettingsErrors[keyof UpdateDeviceSettingsErrors]

export type UpdateDeviceSettingsResponses = {
  /**
   * Operation result.
   */
  200: MessageResponse
}

export type UpdateDeviceSettingsResponse =
  UpdateDeviceSettingsResponses[keyof UpdateDeviceSettingsResponses]

export type SwitchNextContentData = {
  body?: never
  path: {
    /**
     * Dot. device serial number.
     */
    deviceId: string
  }
  query?: never
  url: '/api/authV2/open/device/{deviceId}/next'
}

export type SwitchNextContentErrors = {
  /**
   * Invalid or missing API key.
   */
  401: ErrorResponse
  /**
   * Device or resource not found.
   */
  404: ErrorResponse
  /**
   * Rate limit exceeded. Limit is 10 requests per second.
   */
  429: ErrorResponse
}

export type SwitchNextContentError = SwitchNextContentErrors[keyof SwitchNextContentErrors]

export type SwitchNextContentResponses = {
  /**
   * Operation result.
   */
  200: MessageResponse
}

export type SwitchNextContentResponse = SwitchNextContentResponses[keyof SwitchNextContentResponses]

export type DisplayTextData = {
  body: TextContentRequest
  path: {
    /**
     * Dot. device serial number.
     */
    deviceId: string
  }
  query?: never
  url: '/api/authV2/open/device/{deviceId}/text'
}

export type DisplayTextErrors = {
  /**
   * Invalid or missing API key.
   */
  401: ErrorResponse
  /**
   * Device or resource not found.
   */
  404: ErrorResponse
  /**
   * Rate limit exceeded. Limit is 10 requests per second.
   */
  429: ErrorResponse
}

export type DisplayTextError = DisplayTextErrors[keyof DisplayTextErrors]

export type DisplayTextResponses = {
  /**
   * Operation result.
   */
  200: MessageResponse
}

export type DisplayTextResponse = DisplayTextResponses[keyof DisplayTextResponses]

export type DisplayImageData = {
  body: ImageContentRequest
  path: {
    /**
     * Dot. device serial number.
     */
    deviceId: string
  }
  query?: never
  url: '/api/authV2/open/device/{deviceId}/image'
}

export type DisplayImageErrors = {
  /**
   * Invalid or missing API key.
   */
  401: ErrorResponse
  /**
   * Device or resource not found.
   */
  404: ErrorResponse
  /**
   * Rate limit exceeded. Limit is 10 requests per second.
   */
  429: ErrorResponse
}

export type DisplayImageError = DisplayImageErrors[keyof DisplayImageErrors]

export type DisplayImageResponses = {
  /**
   * Operation result.
   */
  200: MessageResponse
}

export type DisplayImageResponse = DisplayImageResponses[keyof DisplayImageResponses]

export type DisplayCanvasData = {
  body: CanvasContentRequest
  path: {
    /**
     * Dot. device serial number.
     */
    deviceId: string
  }
  query?: never
  url: '/api/authV2/open/device/{deviceId}/canvas'
}

export type DisplayCanvasErrors = {
  /**
   * Invalid or missing API key.
   */
  401: ErrorResponse
  /**
   * Device or resource not found.
   */
  404: ErrorResponse
  /**
   * Rate limit exceeded. Limit is 10 requests per second.
   */
  429: ErrorResponse
}

export type DisplayCanvasError = DisplayCanvasErrors[keyof DisplayCanvasErrors]

export type DisplayCanvasResponses = {
  /**
   * Operation result.
   */
  200: MessageResponse
}

export type DisplayCanvasResponse = DisplayCanvasResponses[keyof DisplayCanvasResponses]

export type ListDeviceTasksData = {
  body?: never
  path: {
    /**
     * Dot. device serial number.
     */
    deviceId: string
    /**
     * Device task group to list.
     */
    taskType: 'loop' | 'fixed'
  }
  query?: never
  url: '/api/authV2/open/device/{deviceId}/{taskType}/list'
}

export type ListDeviceTasksErrors = {
  /**
   * Invalid or missing API key.
   */
  401: ErrorResponse
  /**
   * Device or resource not found.
   */
  404: ErrorResponse
  /**
   * Rate limit exceeded. Limit is 10 requests per second.
   */
  429: ErrorResponse
}

export type ListDeviceTasksError = ListDeviceTasksErrors[keyof ListDeviceTasksErrors]

export type ListDeviceTasksResponses = {
  /**
   * Device tasks.
   */
  200: Array<DeviceTask>
}

export type ListDeviceTasksResponse = ListDeviceTasksResponses[keyof ListDeviceTasksResponses]
